apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  annotations:
    deployment-analyzer/depends-on: "api-gateway"
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: frontend:latest